[package]
name = "mosup"
version = "0.1.0"
description = "(MO)toko (S)table memory (UP)grade system preprocessor"
repository = "https://github.com/Neutrinomic/mosup"
keywords = [ ]
license = "MIT"

[dependencies]

